version: "3"
services:

  web:
     image: steveltn/https-portal:1
     environment:
        DOMAINS: 'recommender.organicity.eu -> http://recommender:7070, recommenderq.organicity.eu -> http://recommender:8000'
        STAGE: 'production' # Set this on local for using self-signed certificate
        #STAGE: local # In development
     ports:
       - 80:80
       - 443:443
     networks:
       - backend
       - frontend
  
networks:
  frontend:
  backend:

