version: "3"
services:

  web:
     image: steveltn/https-portal:1
     environment:
        DOMAINS: 'recommender.organicity.eu -> http://recommender:7070, recommenderq.organicity.eu -> http://recommender:8000'
        STAGE: 'production' # Set this on local for using self-signed certificate
        #STAGE: local # In development
     ports:
       - 80:80
       - 443:443
     networks:
       - backend
       - frontend

  piodb:
    image: postgres:9.6
    environment:
      POSTGRES_DB: pio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    networks:
      - backend

  pioengine:
    image: synchronicityiot/recommender:latest
    environment:
      PIO_STORAGE_SOURCES_PGSQL_TYPE: jdbc
      PIO_STORAGE_SOURCES_PGSQL_URL: jdbc:postgresql://piodb/pio
      PIO_STORAGE_SOURCES_PGSQL_USERNAME: admin
      PIO_STORAGE_SOURCES_PGSQL_PASSWORD: 1234
    ports:
      - 7070:7070
      - 8000:8000
    networks:
      - backend
    command: ["/UR/wait-for-it.sh", "piodb:5432", "--", "/UR/boot.sh"]

networks:
  frontend:
  backend:
