web:
  image: steveltn/https-portal:1
  links:
    - recommender
  environment:
    DOMAINS: 'recommender.organicity.eu -> http://recommender:7070, recommenderq.organicity.eu -> http://recommender:8000'
    STAGE: 'production' # Set this on local for using self-signed certificate
    #STAGE: local # In development
  restart: unless-stopped
  ports:
    - 80:80
    - 443:443
    #  volumes:
    #    - ./nginx/cors.conf:/etc/nginx/cors.conf
    #    - ./nginx/location.conf/:/etc/nginx/location.conf
    #    Inside this file, put shared config - like 'include cors.conf;' if needed.
    #    - ./nginx/default.ssl.conf.erb/:/var/lib/nginx-conf/default.ssl.conf.erb

recommender:
  build: .
  dockerfile: Dockerfile
  ports:
    - 7070:7070
    - 8000:8000

# If we need our data to be saved on disk, and not only in the container
#  volumes:
#    - ./hbasedata/:/hbasedata/
#    - ./elasticdata/:/elasticdata/
